/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ControlAulas;

import Inicio.Arranque;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GermanV
 */
public class Control1 extends javax.swing.JFrame implements Runnable {
/////////////////////////////////////////////////////////////////////////////////

    int crono = 0, min = 0, seg = 0, ds = 0;//unidades de medida
    Date horafs;
    String fechaActual, horas, minutos, segundos, horaf, codigo;
    // clase calendar
    Calendar calendario;
    // hilo para ejecutar tarea
    Thread h1, h2;
/////////////////////////////////////////////////////////////////////////////
    PreparedStatement pst;
    conectar cc = new conectar();
    Connection cn = cc.conexion();
    Date hora;
    String hora1, sql, conse1;

    public Control1(String conse, String cod) throws SQLException {
        initComponents();

        conse1 = conse;
        codigo = cod;
        System.out.println(codigo);
        setLocationRelativeTo(null);
        ////////////////////////////////////////////////////////////////////////////////////////
        //  instancia la tarea
        h1 = new Thread(this);
        h2 = new Thread(this);
        // inicia la tarea
        h1.start();
        h2.start();
        ///////////////////////////////////////////////////////////////////////////////////

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ControlAulas/univalle.png"));
        return retValue;
    }

    private Control1() {
        initComponents();

        setLocationRelativeTo(null);
        ///////////////////////////////////////////////////////////////////////////
        //  instancia la tarea
        h1 = new Thread(this);
        h2 = new Thread(this);
        // inicia la tarea
        h1.start();
        h2.start();
        //////////////////////////////////////////////////////////////////////////        
    }
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////

    @Override
    public void run() {
        // buscar info sobree current, crea una hilo para el caluclo de la hora
        Thread ct = Thread.currentThread();
        Thread AG = Thread.currentThread();
        while (AG == h2) {
            //metodo instancia
            autoGuardado();
            try {
                usuario();
            } catch (SQLException ex) {
                Logger.getLogger(Control1.class.getName()).log(Level.SEVERE, null, ex);
            }
            // modificcaa la etiqueta del frame y mnuesra los valores de h m s q ue son string            
            try {
                // iniciar tarea despues de...
                Thread.sleep(60000);
            } catch (InterruptedException e) {
            }
        }
        while (ct == h1) {//ciclo infinito
            if (ds == 99) {//si los decisegundos son iguales a 99
                ds = 0;//decisegundo vuelve a empezar en cero
                seg++;//y aumenta un segundo
            }
            if (seg == 59) {//si los segundos son iguales a 59
                seg = 0;//segundo vuelve a empezar en cero
                min++;//y aumenta un minuto
            }
            if (min == 59) {//si los minutos son iguales a 59
                min = 0;//minuto vuelve a empezar en cero
                crono++;//y aumenta una hora
            }
            ds++;//aumentan las decimas de segundo

            lbHora.setText(crono + ":" + min + ":" + seg);//se muestra en el jlabel
            try {
                h1.sleep(10);//que duerma una decima de segundo

            } catch (java.lang.InterruptedException ie) {
                System.out.println(ie.getMessage());
            }
        }
        //////////////////////////////////////////////////////////////////////////////////////////////////////

    }

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCerrarCesion = new javax.swing.JButton();
        lbHora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LbUsuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Control Usuario");
        setBackground(new java.awt.Color(255, 255, 255));
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(197, 37, 37));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Control Maquina");

        btnCerrarCesion.setBackground(new java.awt.Color(255, 204, 204));
        btnCerrarCesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCerrarCesion.setText("Cerrar Sesión");
        btnCerrarCesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarCesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarCesionActionPerformed(evt);
            }
        });

        lbHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHora.setForeground(new java.awt.Color(255, 0, 0));
        lbHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHora.setText("Hora Inicio");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Tiempo:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Bienvenido:");

        LbUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LbUsuario.setForeground(new java.awt.Color(255, 0, 0));
        LbUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbUsuario.setText("Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 71, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(89, 89, 89))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrarCesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHora)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Como salir ?");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cambiar Contraseña");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de...");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu2MousePressed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarCesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarCesionActionPerformed
        horafs = new Date();
        SimpleDateFormat formato1 = new SimpleDateFormat("HH:mm:ss");
        horaf = formato1.format(horafs);
        if (conse1 != null) {
            sql = "Update bitacora Set horafin='" + horaf + "' where codigo='" + conse1 + "'";

            try {
                pst = cn.prepareStatement(sql);
                pst.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No ");
                Logger.getLogger(Control1.class.getName()).log(Level.SEVERE, null, ex);
            }
            Arranque bloqueo = new Arranque();
            bloqueo.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No es posible actualizar informacion\nAcerquese a un Administrador");
        }
    }//GEN-LAST:event_btnCerrarCesionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(this, "Para salir debe dar clic en el boton\nCerrar Sesión");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        cambioContraseña cambiar = new cambioContraseña(this, codigo);
        cambiar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MousePressed
        Creditos creditos = new Creditos();
        creditos.setVisible(true);
    }//GEN-LAST:event_jMenu2MousePressed
    public void autoGuardado() {
        horafs = new Date();
        SimpleDateFormat formato1 = new SimpleDateFormat("HH:mm:ss");
        horaf = formato1.format(horafs);
        if (conse1 != null) {
            sql = "Update bitacora Set horafin='" + horaf + "' where codigo='" + conse1 + "'";

            try {
                pst = cn.prepareStatement(sql);
                pst.executeUpdate();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "No ");
                Logger.getLogger(Control1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No es posible actualizar informacion\nAcerquese a un Administrador");
        }
    }

    public void usuario() throws SQLException {
        String sql1, usu;
        sql1 = "select concat(nombre1,' ',apellido1) from estudiante where codigo='" + codigo + "'";
        PreparedStatement pst1;
        conectar cc1 = new conectar();
        Connection cn1 = cc1.conexion();
        ResultSet rs1;
        ///////////////////*/////////////////*//////////////////////
        pst1 = cn1.prepareStatement(sql1);
        rs1 = pst1.executeQuery();
        rs1.first();
        usu = rs1.getString(1);
        LbUsuario.setText(usu);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Control1().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbUsuario;
    private javax.swing.JButton btnCerrarCesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables

}
